export const authTypes = {
  AUTH_SIGN_IN: 'API:AUTH_SIGN_IN',
  AUTH_SIGN_IN_SUCCESS: 'AUTH_SIGN_IN_SUCCESS',

  AUTH_SIGN_UP: 'API:AUTH_SIGN_UP',
  AUTH_SIGN_UP_SUCCESS: 'AUTH_SIGN_UP_SUCCESS',

  AUTH_LOGOUT: 'AUTH_LOGOUT'
}