export const projectTypes = {
  PROJECTS_GET: 'API:PROJECTS_GET',
  PROJECTS_GET_SUCCESS: 'PROJECTS_GET_SUCCESS',

  PROJECT_CREATE: 'API:PROJECT_CREATE',
  PROJECT_CREATE_SUCCESS: 'PROJECT_CREATE_SUCCESS',
}